name: "Report on open PRs"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Report number of open PRs to Uptime Kuma
      run: |
        pr_count=$(curl -s https://api.github.com/repos/dvdl16/simsafari-lodge-booking-payment-lambda/pulls | jq length)
        curl -X GET "${{ secrets.UPTIME_KUMA_URL }}?status=up&ping=$pr_count&msg=OK"
