name: Trigger Infra Repo Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-other-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger GitHub Action in Another Repository
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.INFRA_REPO_TRIGGER_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        "https://api.github.com/repos/dvdl16/simsafari-lodge-booking-infra/dispatches" \
        -d '{"event_type": "PAYMENT_LAMBDA_UPDATED"}'
